# Chapter 4 - Matrix Rank

In [1]:
import numpy as np

## Calculate the Rank of a Matrix

In [2]:
# create a matrix
m = 4
n = 6

A = np.random.randn(m,n)

# calculate its rank
ra = np.linalg.matrix_rank(A)
print("The rank of matrix A is {}". format(ra))

The rank of matrix A is 4


In [3]:
# set the last column to be the repetition of the penultimate column
B = A
B[:,-1] = B[:, -2]

# calculate the rank
rb = np.linalg.matrix_rank(B)
print(B)
print()
print("The rank of Matrix B is {}".format(rb))

[[ 0.57678435 -0.78239    -0.39191178 -0.72329224 -0.07088898 -0.07088898]
 [ 2.03537089 -0.82088645  0.15695092 -0.20260354  0.35436399  0.35436399]
 [ 0.5396335   0.12370888 -0.2054872   0.51636517 -0.34007243 -0.34007243]
 [-0.31107796  1.28365524 -1.80461945  2.13838171 -0.8877294  -0.8877294 ]]

The rank of Matrix B is 4


In [4]:
# Create a repeat of the last row
B = A
B[-1,:] = B[-2,:]
rb = np.linalg.matrix_rank(B)
print(B)
print()
print("The rank of Matrix B is {}".format(rb))

[[ 0.57678435 -0.78239    -0.39191178 -0.72329224 -0.07088898 -0.07088898]
 [ 2.03537089 -0.82088645  0.15695092 -0.20260354  0.35436399  0.35436399]
 [ 0.5396335   0.12370888 -0.2054872   0.51636517 -0.34007243 -0.34007243]
 [ 0.5396335   0.12370888 -0.2054872   0.51636517 -0.34007243 -0.34007243]]

The rank of Matrix B is 3


In [5]:
# Add noise to a rank deficient matrix
A = np.round(10* np.random.randn(m,m))

# reduce the rank
A[:, -1] = A[:, -2]

# introduce some noise
noiseamp = 0.001

# ad noise to the matrix
B = A + noiseamp*np.random.randn(m,m)

rankA = np.linalg.matrix_rank(A)
rankB = np.linalg.matrix_rank(B)

print("Rank without noise is {}".format(rankA))
print("Rank with noise is {}".format(rankB))

Rank without noise is 3
Rank with noise is 4


In [6]:
# Add noise to a rank deficient matrix: With this noise rank doesnt change
A = np.round(10* np.random.randn(m,m))

# reduce the rank
A[:, -1] = A[:, -2]

# introduce some noise
noiseamp = 0.00000000000001

# ad noise to the matrix
B = A + noiseamp*np.random.randn(m,m)

rankA = np.linalg.matrix_rank(A)
rankB = np.linalg.matrix_rank(B)

print("Rank without noise is {}".format(rankA))
print("Rank with noise is {}".format(rankB))

Rank without noise is 3
Rank with noise is 3


## Rank of Added and Multiplied Matrix

If we know the rank(A) and rank(B), what can we infer about rank(A+B) and rank(AxB)? There are some rules about deciding on the upper boundary, i.e. the maximum possible value of rank(A+B) and rank(AxB).

In [7]:
# Some examples
A = np.array([[1,2,3], 
              [3,4,1],
              [5,9,1]])
B = np.array([[0,3,5], 
              [1,0,4], 
              [3,3,0]])
C = A+B
print("Rank of A is {}".format(np.linalg.matrix_rank(A)))
print()
print("Rank of B is {}".format(np.linalg.matrix_rank(B)))
print()
print("Rank of A + B is {}".format(np.linalg.matrix_rank(C)))

Rank of A is 3

Rank of B is 3

Rank of A + B is 3


In [8]:
A = np.array([[1,1,1], 
              [2,2,2], 
              [3,3,0]])

B = np.zeros((3,3))

C = A+B
print("Rank of A is {}".format(np.linalg.matrix_rank(A)))
print()
print("Rank of B is {}".format(np.linalg.matrix_rank(B)))
print()
print("Rank of A + B is {}".format(np.linalg.matrix_rank(C)))

Rank of A is 2

Rank of B is 0

Rank of A + B is 2


In [9]:
A = np.array([[1,2,0], 
              [3,4,0], 
              [5,9,0]])

B = np.array([[0,0,5], 
              [0,0,4], 
              [0,0,1]])

C = A+B
print("Rank of A is {}".format(np.linalg.matrix_rank(A)))
print()
print("Rank of B is {}".format(np.linalg.matrix_rank(B)))
print()
print("Rank of A + B is {}".format(np.linalg.matrix_rank(C)))

Rank of A is 2

Rank of B is 1

Rank of A + B is 3


In [10]:
A = np.array([[-1,-4,2], 
              [-4,2,-1], 
              [9,4,-3]])

B = np.array([[1,4,0], 
              [4,-2,0], 
              [-9,-4,0]])

C = A+B
print("Rank of A is {}".format(np.linalg.matrix_rank(A)))
print()
print("Rank of B is {}".format(np.linalg.matrix_rank(B)))
print()
print("Rank of A + B is {}".format(np.linalg.matrix_rank(C)))

Rank of A is 3

Rank of B is 2

Rank of A + B is 1


For the same matrices apply multiplication (dot product)

In [11]:
A = np.array([[1,2,3], 
              [3,4,1],
              [5,9,1]])
B = np.array([[0,3,5], 
              [1,0,4], 
              [3,3,0]])
C = A@B
print("Rank of A is {}".format(np.linalg.matrix_rank(A)))
print()
print("Rank of B is {}".format(np.linalg.matrix_rank(B)))
print()
print("Rank of AxB is {}".format(np.linalg.matrix_rank(C)))

Rank of A is 3

Rank of B is 3

Rank of AxB is 3


In [12]:
A = np.array([[1,1,1], 
              [2,2,2], 
              [3,3,0]])

B = np.zeros((3,3))

C = A@B
print("Rank of A is {}".format(np.linalg.matrix_rank(A)))
print()
print("Rank of B is {}".format(np.linalg.matrix_rank(B)))
print()
print("Rank of AxB is {}".format(np.linalg.matrix_rank(C)))

Rank of A is 2

Rank of B is 0

Rank of AxB is 0


In [13]:
A = np.array([[1,2,0], 
              [3,4,0], 
              [5,9,0]])

B = np.array([[0,0,5], 
              [0,0,4], 
              [0,0,1]])

C = A@B
print("Rank of A is {}".format(np.linalg.matrix_rank(A)))
print()
print("Rank of B is {}".format(np.linalg.matrix_rank(B)))
print()
print("Rank of AxB is {}".format(np.linalg.matrix_rank(C)))

Rank of A is 2

Rank of B is 1

Rank of AxB is 1


In [14]:
A = np.array([[-1,-4,2], 
              [-4,2,-1], 
              [9,4,-3]])

B = np.array([[1,4,0], 
              [4,-2,0], 
              [-9,-4,0]])

C = A@B
print("Rank of A is {}".format(np.linalg.matrix_rank(A)))
print()
print("Rank of B is {}".format(np.linalg.matrix_rank(B)))
print()
print("Rank of AxB is {}".format(np.linalg.matrix_rank(C)))

Rank of A is 3

Rank of B is 2

Rank of AxB is 2


## Reduced Rank Matrix via Multiplication

In [15]:
# create a reduced rank matrix using multiplication
A = np.random.randn(10,4)
B = np.random.randn(4,10)
C = A@B
print("The shape of C is {}".format(np.shape(C)))
print()
print("The rank of C is {}".format(np.linalg.matrix_rank(C)))

The shape of C is (10, 10)

The rank of C is 4


In [16]:
# Generalize for matrixes of any size
m = 50
n = 70
r =10

A = np.random.randn(m,r) @ np.random.randn(r,n)
print("The shape of A is {}".format(np.shape(A)))
print()
print("The rank of A is {}".format(np.linalg.matrix_rank(A)))

The shape of A is (50, 70)

The rank of A is 10


## Scalar Multiplication and Rank

In [17]:
# define a full-rank and a reduced-rank matrix
m = 5
n = 4

A = np.random.randn(m,n)
B = np.random.randn(m, n-1)

print("The rank of A is {}".format(np.linalg.matrix_rank(A)))
print("The rank of B is {}".format(np.linalg.matrix_rank(B)))

The rank of A is 4
The rank of B is 3


In [18]:
# define a scalar l and re-calculate the ranks
# No change
l = 12345
print("The rank of A is {}".format(np.linalg.matrix_rank(l*A)))
print("The rank of B is {}".format(np.linalg.matrix_rank(l*B)))

The rank of A is 4
The rank of B is 3


In [19]:
# Multiply l with the ran of matrix
l = 2
print("The rank of A is {}".format(l*np.linalg.matrix_rank(A)))
print("The rank of B is {}".format(l*np.linalg.matrix_rank(B)))

The rank of A is 8
The rank of B is 6


Since rank(lxA) is not equal to lxrank(A), we say that rank is not a linear operator

## Rank of ATA and AAT

In [20]:
# Define a matrix
m = 14
n = 3
A = np.random.randn(m,n)

# compute the multiplications
AtA = A.T @ A
AAt = A @ A.T

print("AtA size is {}x{} and rank is {}".format(AtA.shape[0],AtA.shape[1], np.linalg.matrix_rank(AtA)))
print("AAt size is {}x{} and rank is {}".format(AAt.shape[0],AAt.shape[1], np.linalg.matrix_rank(AAt)))

AtA size is 3x3 and rank is 3
AAt size is 14x14 and rank is 3


## Making a Full-Rank Matrix by Shifting

In [21]:
m = 30

A = np.random.randn(m,m)
A = np.round(10* A.T @A)
print("The rank of A is {}".format(np.linalg.matrix_rank(A)))
# Reduce the rank
A[:,0] = A[:,1]
print("The reduced rank of A is {}".format(np.linalg.matrix_rank(A)))

The rank of A is 30
The reduced rank of A is 29


In [22]:
# define an lambda value
l = 0.01
B = A + l*np.eye(m)

print("The rank of B is {}".format(np.linalg.matrix_rank(B)))

The rank of B is 30


In [23]:
# Create a very low rank matrix and then increase the rank
m = 13
n = 4
A = np.random.randn(m,n)
print(np.linalg.matrix_rank(A))
A = np.round(10*A @A.T)
print(np.linalg.matrix_rank(A))

4
13


In [24]:
print(A)

[[ 54.  10.  19.  25. -17. -11.   2.  -4.  18.  14.  -3.  -3.  22.]
 [ 10. 106.  -2. -23. -15.  -3.  -6. -13. -63.  11. -15.  38.   8.]
 [ 19.  -2.  44.  -4.  -5. -18.  12.  -8.  13.  -0.  -9. -50.  -2.]
 [ 25. -23.  -4.  29.  -0.  -6.   6.   5.  20.  20.  16.  14.  19.]
 [-17. -15.  -5.  -0.  13.  -4.   9.   4.  -4.  11.  14.   4.  -1.]
 [-11.  -3. -18.  -6.  -4.  17. -15.   2.   2. -21. -10.   8. -10.]
 [  2.  -6.  12.   6.   9. -15.  16.   1.  -2.  21.  15.  -4.   8.]
 [ -4. -13.  -8.   5.   4.   2.   1.   4.   4.   3.   7.   7.   1.]
 [ 18. -63.  13.  20.  -4.   2.  -2.   4.  52. -15.  -2. -37.  -2.]
 [ 14.  11.  -0.  20.  11. -21.  21.   3. -15.  48.  30.  31.  26.]
 [ -3. -15.  -9.  16.  14. -10.  15.   7.  -2.  30.  26.  22.  14.]
 [ -3.  38. -50.  14.   4.   8.  -4.   7. -37.  31.  22.  86.  22.]
 [ 22.   8.  -2.  19.  -1. -10.   8.   1.  -2.  26.  14.  22.  19.]]


## Vector in the Span of a Set

In [25]:
# Determine whether the following vector is in the span of these sets
v = np.array([[1, 2, 3, 4]]).T

S = np.vstack(([4,3,6,2], [0,4,0,1])).T
T = np.vstack(([1,2,2,2], [0,0,1,2])).T

print(v)
print()
print(S)
print()
print(T)

[[1]
 [2]
 [3]
 [4]]

[[4 0]
 [3 4]
 [6 0]
 [2 1]]

[[1 0]
 [2 0]
 [2 1]
 [2 2]]


In [26]:
print("The rank of S is {}".format(np.linalg.matrix_rank(S)))
print("The rank of T is {}".format(np.linalg.matrix_rank(T)))

The rank of S is 2
The rank of T is 2


In [27]:
# Concatenate the vector to create an augmented matrix
Sv = np.concatenate((S,v), axis = 1)
Tv = np.concatenate((T,v), axis = 1)
print(Sv)
print()
print(Tv)

[[4 0 1]
 [3 4 2]
 [6 0 3]
 [2 1 4]]

[[1 0 1]
 [2 0 2]
 [2 1 3]
 [2 2 4]]


In [28]:
print("The rank of Sv is {}".format(np.linalg.matrix_rank(Sv)))
print("The rank of Tv is {}".format(np.linalg.matrix_rank(Tv)))

The rank of Sv is 3
The rank of Tv is 2


v is not in the span of set S but it is in the span of set T because for the former it increases the rank by 1 while in the later it doesnt change the rank.