# Section02_Matrices

In [1]:
import numpy as np

## Types of Matrices

In [2]:
# Square Matrix
S = np.random.randn(5,5)
print(S)

[[-0.96246375 -1.72008639  0.77045398  0.02128926 -0.29224334]
 [-0.26895609  0.18481043 -0.4389134  -1.88264574 -0.01040493]
 [-0.45968276  1.02954043 -0.67524064 -0.41323925 -1.24332614]
 [-0.00771975 -0.01302362  0.00299013 -1.77813366 -0.82818233]
 [-0.42971523 -0.64202428 -0.17656742 -0.91503591 -0.90558717]]


In [3]:
# Rectangular Matrix
R = np.random.randn(5,2)
print(R)

[[-0.4266198   0.99012406]
 [-1.04807432 -0.82124092]
 [ 0.84360835 -0.6774923 ]
 [ 0.62800479 -0.30564061]
 [ 0.68935645 -0.08948812]]


In [4]:
# Identity Matrix
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# Zero Matrix: Tupple as input
Z = np.zeros((4,4))
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
# Zero matrix for complex numbers
Z = np.zeros((4,4), dtype = complex)
print(Z)

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [7]:
# Diagonal Matrix
D = np.diag([1, 2, 3, 5, 2])
print(D)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]


In [8]:
# Triangular matrices from full matrix
S = np.random.randn(5,5)
print(S)

[[-2.61895555  0.3613667   0.75679752  0.30633308 -1.16839028]
 [ 0.25486216  0.34899015 -1.97995028  0.73473176 -1.15874902]
 [-0.23457514  1.89955683 -1.37803667  1.9633485  -0.95923191]
 [-2.14934278  0.27007118 -1.46639644 -1.02024686 -0.09340059]
 [ 0.01571529 -0.06619766  0.52104262  0.71775523  0.92120492]]


In [9]:
# Upper triangular
U = np.triu(S)
print(U)

[[-2.61895555  0.3613667   0.75679752  0.30633308 -1.16839028]
 [ 0.          0.34899015 -1.97995028  0.73473176 -1.15874902]
 [ 0.          0.         -1.37803667  1.9633485  -0.95923191]
 [ 0.          0.          0.         -1.02024686 -0.09340059]
 [ 0.          0.          0.          0.          0.92120492]]


In [10]:
# Lower Triangular
L = np.tril(S)
print(L)

[[-2.61895555  0.          0.          0.          0.        ]
 [ 0.25486216  0.34899015  0.          0.          0.        ]
 [-0.23457514  1.89955683 -1.37803667  0.          0.        ]
 [-2.14934278  0.27007118 -1.46639644 -1.02024686  0.        ]
 [ 0.01571529 -0.06619766  0.52104262  0.71775523  0.92120492]]


In [11]:
# Concatenate Matrices (sizes must match!)
A = np.random.randn(3,2)
print(A)

[[-0.02929801  0.02529126]
 [-0.61604756  0.51734347]
 [-1.8868881  -0.24104273]]


In [12]:
B = np.random.randn(3,4)
print(B)

[[ 0.70846679  1.74603369  0.46432743 -2.08533446]
 [ 0.7131712  -0.95446717  0.58189096 -0.38988547]
 [ 1.31698133  1.05299473 -0.63991068 -1.2368758 ]]


In [13]:
C = np.concatenate((A,B), axis = 1)
print(C)

[[-0.02929801  0.02529126  0.70846679  1.74603369  0.46432743 -2.08533446]
 [-0.61604756  0.51734347  0.7131712  -0.95446717  0.58189096 -0.38988547]
 [-1.8868881  -0.24104273  1.31698133  1.05299473 -0.63991068 -1.2368758 ]]


## Matrix Addition and Subtraction

In [14]:
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

In [15]:
# Add A & B
# A + B

In [16]:
# Add B + C
#B + C

In [17]:
# Add A + C
A + C

array([[-0.54808387,  0.79539661, -1.28476718, -2.03106064],
       [ 0.36329764, -0.97707471,  1.33053193,  1.93864204],
       [ 1.1107575 , -1.24161689,  0.75363376, -2.67650704],
       [ 1.79468712, -0.25570537, -0.37849101, -2.41365892],
       [-2.15828139,  1.13875521,  0.49762436, -0.91744722]])

In [18]:
# Shifting a msatrix
l = 0.3
N = 5
D = np.random.randn(N, N)
print(D)

[[ 1.33314953 -0.29258705  0.60844665  0.38889213  0.62640369]
 [ 0.0132283  -0.39097495 -0.61963929 -0.8292714   0.6055549 ]
 [-0.89043006 -0.25004752 -0.43612179 -0.25340628 -0.27328172]
 [-1.21014845  0.65661331  0.60334456  0.36993717 -0.39184488]
 [ 1.35099285  0.53550638  2.68309899 -1.23524814 -0.73672113]]


In [19]:
Ds = D + l*np.eye(N)
print(Ds)

[[ 1.63314953 -0.29258705  0.60844665  0.38889213  0.62640369]
 [ 0.0132283  -0.09097495 -0.61963929 -0.8292714   0.6055549 ]
 [-0.89043006 -0.25004752 -0.13612179 -0.25340628 -0.27328172]
 [-1.21014845  0.65661331  0.60334456  0.66993717 -0.39184488]
 [ 1.35099285  0.53550638  2.68309899 -1.23524814 -0.43672113]]


In [20]:
# Scalar Multiplication
M = np.array([[1, 2], [2, 5]])
s = 2
print(M*s)
print(s*M)

[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


## Coding Challenge

In [21]:
# Question: Test for some random MXN matrices whether s(A+B) = aA + sB
# define matrix sizes
m = 7
n = 5

# create two random matrices
A = np.random.randn(m, n)
B = np.random.randn(m, n)

# define a random scalar
s = np.random.randn()

In [22]:
# Compute both sides of the equation

In [23]:
res1 = s*(A + B)
res2 = s*A + s*B
print(res1)
print(res2)

[[ 0.05892387 -0.03301921  0.30651892 -0.53459055 -0.07476617]
 [-0.73231557  0.09237637  0.4132418  -0.00329444 -0.20214573]
 [ 0.41545159 -0.45339671 -0.1359277   0.66050264 -0.3825436 ]
 [-0.33680359  0.08482693  0.26078525  0.29131337 -0.63355073]
 [ 0.38029212 -0.71948682  0.21851926  0.36495559 -0.46877725]
 [-0.07825128  0.52668839  0.57696737  0.78822945  0.68903148]
 [ 0.23695308 -0.25311495  0.10684189 -0.23396193  0.17414751]]
[[ 0.05892387 -0.03301921  0.30651892 -0.53459055 -0.07476617]
 [-0.73231557  0.09237637  0.4132418  -0.00329444 -0.20214573]
 [ 0.41545159 -0.45339671 -0.1359277   0.66050264 -0.3825436 ]
 [-0.33680359  0.08482693  0.26078525  0.29131337 -0.63355073]
 [ 0.38029212 -0.71948682  0.21851926  0.36495559 -0.46877725]
 [-0.07825128  0.52668839  0.57696737  0.78822945  0.68903148]
 [ 0.23695308 -0.25311495  0.10684189 -0.23396193  0.17414751]]


In [24]:
# SOme small differences due to rounding, otherwise its zero
res1 - res2

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -1.38777878e-17],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -4.33680869e-19,  2.77555756e-17],
       [ 0.00000000e+00,  5.55111512e-17,  0.00000000e+00,
         1.11022302e-16,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  5.55111512e-17,
         0.00000000e+00,  1.11022302e-16],
       [ 0.00000000e+00,  0.00000000e+00, -2.77555756e-17,
         5.55111512e-17, -5.55111512e-17],
       [ 0.00000000e+00, -1.11022302e-16,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.38777878e-17,
         0.00000000e+00, -2.77555756e-17]])

## Matrix Transposition

In [25]:
# Create a matrix
M = np.array([[1, 2, 3],
             [2, 3, 4]])
print(M)

[[1 2 3]
 [2 3 4]]


In [26]:
print(M.T)

[[1 2]
 [2 3]
 [3 4]]


In [27]:
print(M.T.T)

[[1 2 3]
 [2 3 4]]


In [28]:
print(np.transpose(M))

[[1 2]
 [2 3]
 [3 4]]


In [29]:
# Be careful with complex matrices
C = np.array([[4+1j, 3, 2-4j]])
print(C)

[[4.+1.j 3.+0.j 2.-4.j]]


In [30]:
print(C.T)

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]


In [31]:
print(np.transpose(C))

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]


In [32]:
# Hemitian transposition
print(np.matrix(C).H)

[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]


## Diagonal and Trace

In [33]:
# define a matrix
M = np.round(5* np.random.randn(4,4))
print(M)

[[ -3.   2.   0.   6.]
 [ 12.   1.  -3. -14.]
 [  2.   2.  10.  -3.]
 [ -8.  -5.  -7. -11.]]


In [34]:
# extract the diagonal
d = np.diag(M)
print(d)

[ -3.   1.  10. -11.]


In [35]:
# get a diagonal matrix as output
D = np.diag(d)
print(D)

[[ -3.   0.   0.   0.]
 [  0.   1.   0.   0.]
 [  0.   0.  10.   0.]
 [  0.   0.   0. -11.]]


In [36]:
# Trace
tr = np.trace(M)
print(tr)

-3.0


In [37]:
# trace as sum
tr2 = sum(np.diag(M))
print(tr2)

-3.0


## Code Challenge

In [38]:
# Is trace a linear operator? Is it closed under addition and scalar multiplications
## determine the relationship between tr(A) + tr(B) and tr(A+B)
## determine the relationship between tr(l*A) and l*tr(A)
### if these conditions true, then it is a linear operator

In [39]:
# COndition 1
m = 5
A = np.round(4* np.random.randn(m, m))
B = np.round(4* np.random.randn(m, m))
res1 = np.trace(A) + np.trace(B)
res2 = np.trace(A + B)
print(res1)
print(res2)

-6.0
-6.0


In [40]:
# Condition 2
l = np.random.randn()
np.trace(l*A) == l*np.trace(A)

True

## Broadcasting Matrix Arithmetic

In [41]:
# Create a matrix
A = np.reshape(np.arange(1, 13), (3,4), "F") # F = column, C = row
# C is the default, like in R
print(A)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [42]:
# Define 2 vectors
r = np.array([10, 20, 30, 40])
c = np.array([100, 200, 300])
print(r)
print(c)

[10 20 30 40]
[100 200 300]


In [43]:
# broadcast on the rows
print(A + r)

[[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]


In [44]:
# Broadcast on columns
# print(A + c) this gives an error
print(A + np.reshape(c,(len(c), 1)))

[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]


In [45]:
# Works for explicit column vectors
np.reshape(c,(len(c), 1))

array([[100],
       [200],
       [300]])